[tool.poetry]
name = "toggle-display-input"
version = "0.1.1a2"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
monitorcontrol = "^3.1.0"

[tool.poetry.scripts]
toggle_display_input = "toggle_display_input.toggle_display_input:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
