[tool.poetry]
name = "toggle-display-input"
version = "0.1.1a15"
description = ""
authors = ["Koji Ishii <kojiishi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
monitorcontrol = "^3.1.0"
platformdirs = "^4.3.6"

[tool.poetry.scripts]
toggle-display-input = "toggle_display_input.display:Display.toggle_cmd"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
